version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: o2_database
    environment:
      POSTGRES_USER: o2admin
      POSTGRES_PASSWORD: passo2
      POSTGRES_DB: o2db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
