/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StockImport } from './routes/stock'
import { Route as MovementsImport } from './routes/movements'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StockRoute = StockImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRoute,
} as any)

const MovementsRoute = MovementsImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsImport
      parentRoute: typeof rootRoute
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/stock': typeof StockRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/stock': typeof StockRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/movements': typeof MovementsRoute
  '/stock': typeof StockRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movements' | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movements' | '/stock'
  id: '__root__' | '/' | '/movements' | '/stock'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovementsRoute: typeof MovementsRoute
  StockRoute: typeof StockRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovementsRoute: MovementsRoute,
  StockRoute: StockRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movements",
        "/stock"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/movements": {
      "filePath": "movements.tsx"
    },
    "/stock": {
      "filePath": "stock.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
