/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EditProductImport } from './routes/edit-product'
import { Route as AddImport } from './routes/add'
import { Route as IndexImport } from './routes/index'
import { Route as ProductIndexImport } from './routes/product.index'
import { Route as ProductIdImport } from './routes/product.$id'

// Create/Update Routes

const EditProductRoute = EditProductImport.update({
  id: '/edit-product',
  path: '/edit-product',
  getParentRoute: () => rootRoute,
} as any)

const AddRoute = AddImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductIndexRoute = ProductIndexImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRoute,
} as any)

const ProductIdRoute = ProductIdImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddImport
      parentRoute: typeof rootRoute
    }
    '/edit-product': {
      id: '/edit-product'
      path: '/edit-product'
      fullPath: '/edit-product'
      preLoaderRoute: typeof EditProductImport
      parentRoute: typeof rootRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdImport
      parentRoute: typeof rootRoute
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/edit-product': typeof EditProductRoute
  '/product/$id': typeof ProductIdRoute
  '/product': typeof ProductIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/edit-product': typeof EditProductRoute
  '/product/$id': typeof ProductIdRoute
  '/product': typeof ProductIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/edit-product': typeof EditProductRoute
  '/product/$id': typeof ProductIdRoute
  '/product/': typeof ProductIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/edit-product' | '/product/$id' | '/product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/edit-product' | '/product/$id' | '/product'
  id: '__root__' | '/' | '/add' | '/edit-product' | '/product/$id' | '/product/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  EditProductRoute: typeof EditProductRoute
  ProductIdRoute: typeof ProductIdRoute
  ProductIndexRoute: typeof ProductIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  EditProductRoute: EditProductRoute,
  ProductIdRoute: ProductIdRoute,
  ProductIndexRoute: ProductIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add",
        "/edit-product",
        "/product/$id",
        "/product/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add": {
      "filePath": "add.tsx"
    },
    "/edit-product": {
      "filePath": "edit-product.tsx"
    },
    "/product/$id": {
      "filePath": "product.$id.tsx"
    },
    "/product/": {
      "filePath": "product.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
